# Generated by Django 3.2.14 on 2022-07-20 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdetails',
            name='name',
        ),
        migrations.AddField(
            model_name='listdetails',
            name='authname',
            field=models.CharField(default='ss', max_length=122),
        ),
        migrations.AddField(
            model_name='listdetails',
            name='compdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 20, 20, 15, 45, 428218)),
        ),
        migrations.AddField(
            model_name='listdetails',
            name='compstatus',
            field=models.CharField(default='No', max_length=4),
        ),
        migrations.AddField(
            model_name='listdetails',
            name='creatdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 20, 20, 15, 45, 428218)),
        ),
        migrations.AddField(
            model_name='listdetails',
            name='desc',
            field=models.TextField(default=' '),
        ),
    ]
