# Generated by Django 3.2.14 on 2022-07-20 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20220720_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetails',
            name='compdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 20, 20, 16, 51, 509175)),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='creatdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 20, 20, 16, 51, 509175)),
        ),
    ]
