# Generated by Django 3.2.14 on 2022-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20220720_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetails',
            name='compdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='creatdate',
            field=models.DateField(),
        ),
    ]
