# Generated by Django 3.2.14 on 2022-07-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20220720_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetails',
            name='authname',
            field=models.CharField(max_length=122),
        ),
    ]
