# Generated by Django 3.2.14 on 2022-07-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_alter_listdetails_authname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetails',
            name='authname',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
