# Generated by Django 3.2.14 on 2022-07-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_alter_listdetails_authname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetails',
            name='compdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='creatdate',
            field=models.DateField(null=True),
        ),
    ]
