# Generated by Django 3.2.14 on 2022-07-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20220721_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetails',
            name='compstatus',
            field=models.CharField(default='No', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='desc',
            field=models.TextField(default=' ', null=True),
        ),
    ]
