# Generated by Django 3.2.14 on 2022-07-20 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20220721_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetails',
            name='authname',
            field=models.CharField(default='ss', max_length=122),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='compdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 21, 5, 29, 54, 431193)),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='compstatus',
            field=models.CharField(default='NO', max_length=4),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='creatdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 21, 5, 29, 54, 431193)),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
